const mySet = new Set();
console.log(mySet);
mySet.add(5);
mySet.add(5);
console.log(mySet.add(10));
console.log(mySet.add(115));
console.log(mySet.add(39).add(45).clear());
console.log(mySet.add(24));
console.log(mySet.add(4));
console.log(mySet.add(5));
console.log(mySet);
