const ns = new Set();
console.log(ns);
ns.add(5);
ns.add(5);
console.log(ns.add(10));
console.log(ns.add(115));
console.log(ns.add(10));
console.log(ns.add(4));
console.log(ns.add(5));
console.log(ns);
